; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Mar 21 2025 15:54:10 GMT-0500 (Central Daylight Time)
; ================================================================================

DATANHL9WDDYR1:
	dc.w DATANHL9WDDYR1_0-DATANHL9WDDYR1, DATANHL9WDDYR1_1-DATANHL9WDDYR1
	dc.w DATANHL9WDDYR1_2-DATANHL9WDDYR1, DATANHL9WDDYR1_3-DATANHL9WDDYR1
	dc.w DATANHL9WDDYR1_4-DATANHL9WDDYR1, DATANHL9WDDYR1_5-DATANHL9WDDYR1
	dc.w DATANHL9WDDYR1_6-DATANHL9WDDYR1, DATANHL9WDDYR1_7-DATANHL9WDDYR1
DATANHL9WDDYR1_0: dc.b $A
	dc.b $8, $8, $0, $0, $8
	dc.b $10, $F, $0, $3, $8
	dc.b $10, $F, $0, $13, $28
	dc.b $30, $E, $0, $23, $8
	dc.b $30, $E, $0, $2F, $28
	dc.b $48, $D, $0, $3B, $0
	dc.b $48, $9, $0, $43, $20
	dc.b $48, $0, $0, $49, $38
	dc.b $58, $C, $0, $4A, $8
	dc.b $58, $0, $0, $4E, $28
DATANHL9WDDYR1_1: dc.b $F
	dc.b $48, $E, $1, $BD, $20
	dc.b $38, $5, $1, $C9, $38
	dc.b $40, $0, $1, $CD, $30
	dc.b $48, $0, $1, $CE, $40
	dc.b $60, $0, $1, $CF, $20
	dc.b $10, $E, $0, $4F, $8
	dc.b $10, $E, $0, $5B, $28
	dc.b $18, $1, $0, $67, $48
	dc.b $28, $2, $0, $69, $0
	dc.b $28, $F, $0, $6C, $8
	dc.b $28, $F, $0, $7C, $28
	dc.b $30, $2, $0, $8C, $48
	dc.b $48, $E, $0, $8F, $10
	dc.b $48, $9, $0, $9B, $30
	dc.b $58, $4, $0, $A1, $30
DATANHL9WDDYR1_2: dc.b $11
	dc.b $38, $E, $1, $BD, $28
	dc.b $28, $5, $1, $C9, $40
	dc.b $30, $0, $1, $CD, $38
	dc.b $38, $0, $1, $CE, $48
	dc.b $50, $0, $1, $CF, $28
	dc.b $20, $F, $1, $A9, $8
	dc.b $20, $3, $1, $B9, $28
	dc.b $10, $E, $0, $4F, $8
	dc.b $10, $E, $0, $5B, $28
	dc.b $18, $1, $0, $67, $48
	dc.b $28, $2, $0, $69, $0
	dc.b $28, $F, $0, $6C, $8
	dc.b $28, $F, $0, $7C, $28
	dc.b $30, $2, $0, $8C, $48
	dc.b $48, $E, $0, $8F, $10
	dc.b $48, $9, $0, $9B, $30
	dc.b $58, $4, $0, $A1, $30
DATANHL9WDDYR1_3: dc.b $D
	dc.b $10, $F, $0, $A3, $8
	dc.b $8, $8, $0, $B3, $28
	dc.b $10, $F, $0, $B6, $28
	dc.b $18, $0, $0, $C6, $48
	dc.b $20, $6, $0, $C7, $48
	dc.b $38, $0, $0, $CD, $48
	dc.b $30, $D, $0, $CE, $8
	dc.b $30, $E, $0, $D6, $28
	dc.b $40, $B, $0, $E2, $10
	dc.b $48, $8, $0, $EE, $28
	dc.b $50, $1, $0, $F1, $8
	dc.b $50, $4, $0, $F3, $28
	dc.b $58, $0, $0, $F5, $28
DATANHL9WDDYR1_4: dc.b $B
	dc.b $8, $F, $0, $F6, $10
	dc.b $8, $B, $1, $6, $30
	dc.b $10, $6, $1, $12, $48
	dc.b $28, $E, $1, $18, $18
	dc.b $28, $E, $1, $24, $38
	dc.b $28, $1, $1, $30, $10
	dc.b $40, $E, $1, $32, $10
	dc.b $40, $6, $1, $3E, $30
	dc.b $40, $4, $1, $44, $40
	dc.b $48, $0, $1, $46, $40
	dc.b $58, $8, $1, $47, $18
DATANHL9WDDYR1_5: dc.b $13
	dc.b $28, $E, $1, $E4, $38
	dc.b $18, $5, $1, $F0, $48
	dc.b $40, $8, $1, $F4, $38
	dc.b $48, $4, $1, $F7, $38
	dc.b $10, $F, $1, $4A, $10
	dc.b $8, $4, $1, $5A, $20
	dc.b $0, $B, $1, $5C, $30
	dc.b $8, $0, $1, $68, $48
	dc.b $18, $0, $1, $69, $48
	dc.b $18, $5, $1, $6A, $0
	dc.b $28, $2, $1, $6E, $8
	dc.b $30, $F, $1, $71, $10
	dc.b $20, $D, $1, $81, $30
	dc.b $20, $1, $1, $89, $50
	dc.b $30, $8, $1, $8B, $30
	dc.b $38, $E, $1, $8E, $30
	dc.b $50, $D, $1, $9A, $8
	dc.b $50, $C, $1, $A2, $28
	dc.b $58, $8, $1, $A6, $28
DATANHL9WDDYR1_6: dc.b $F
	dc.b $EC, $F, $2, $D, $E2
	dc.b $C, $F, $2, $1D, $E2
	dc.b $2C, $F, $2, $2D, $E2
	dc.b $EC, $F, $2, $3D, $2
	dc.b $C, $F, $2, $4D, $2
	dc.b $2C, $F, $2, $5D, $2
	dc.b $EC, $F, $2, $6D, $22
	dc.b $C, $F, $2, $7D, $22
	dc.b $2C, $F, $2, $8D, $22
	dc.b $EC, $F, $2, $9D, $42
	dc.b $C, $F, $2, $AD, $42
	dc.b $2C, $F, $2, $BD, $42
	dc.b $EC, $7, $2, $CD, $62
	dc.b $C, $7, $2, $D5, $62
	dc.b $2C, $7, $2, $DD, $62
DATANHL9WDDYR1_7: dc.b $F
	dc.b $EC, $F, $2, $D, $E2
	dc.b $C, $F, $2, $1D, $E2
	dc.b $2C, $F, $2, $2D, $E2
	dc.b $EC, $F, $2, $3D, $2
	dc.b $C, $F, $2, $4D, $2
	dc.b $2C, $F, $2, $5D, $2
	dc.b $EC, $F, $2, $6D, $22
	dc.b $C, $F, $2, $7D, $22
	dc.b $2C, $F, $2, $8D, $22
	dc.b $EC, $F, $2, $9D, $42
	dc.b $C, $F, $2, $AD, $42
	dc.b $2C, $F, $2, $BD, $42
	dc.b $EC, $7, $2, $CD, $62
	dc.b $C, $7, $2, $D5, $62
	dc.b $2C, $7, $2, $DD, $62
	even