; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Mar 22 2025 12:11:33 GMT-0500 (Central Daylight Time)
; ================================================================================

DATAV21JFHJ5PUP:
	dc.w DATAV21JFHJ5PUP_0-DATAV21JFHJ5PUP, DATAV21JFHJ5PUP_1-DATAV21JFHJ5PUP
	dc.w DATAV21JFHJ5PUP_2-DATAV21JFHJ5PUP, DATAV21JFHJ5PUP_3-DATAV21JFHJ5PUP
	dc.w DATAV21JFHJ5PUP_4-DATAV21JFHJ5PUP, DATAV21JFHJ5PUP_5-DATAV21JFHJ5PUP
	dc.w DATAV21JFHJ5PUP_6-DATAV21JFHJ5PUP, DATAV21JFHJ5PUP_7-DATAV21JFHJ5PUP
DATAV21JFHJ5PUP_0: dc.b $8
	dc.b $C, $F, $1, $9F, $8
	dc.b $2C, $F, $1, $AF, $8
	dc.b $4C, $D, $1, $BF, $8
	dc.b $4, $8, $1, $C7, $20
	dc.b $C, $B, $1, $CA, $28
	dc.b $2C, $B, $1, $D6, $28
	dc.b $4C, $5, $1, $E2, $28
	dc.b $14, $7, $1, $E6, $40
DATAV21JFHJ5PUP_1: dc.b $B
	dc.b $6, $F, $1, $EE, $1
	dc.b $6, $F, $1, $FE, $21
	dc.b $6, $7, $2, $E, $41
	dc.b $26, $F, $2, $16, $1
	dc.b $26, $F, $2, $26, $21
	dc.b $26, $7, $2, $36, $41
	dc.b $46, $C, $2, $3E, $1
	dc.b $46, $E, $2, $42, $21
	dc.b $46, $6, $2, $4E, $41
	dc.b $4E, $8, $2, $54, $9
	dc.b $56, $4, $2, $57, $11
DATAV21JFHJ5PUP_2: dc.b $B
	dc.b $F2, $F, $1, $EE, $1
	dc.b $F2, $F, $1, $FE, $21
	dc.b $F2, $7, $2, $E, $41
	dc.b $12, $F, $2, $16, $1
	dc.b $12, $F, $2, $26, $21
	dc.b $12, $7, $2, $36, $41
	dc.b $32, $C, $2, $3E, $1
	dc.b $32, $E, $2, $42, $21
	dc.b $32, $6, $2, $4E, $41
	dc.b $3A, $8, $2, $54, $9
	dc.b $42, $4, $2, $57, $11
DATAV21JFHJ5PUP_3: dc.b $D
	dc.b $FC, $F, $0, $0, $8
	dc.b $F4, $8, $0, $10, $28
	dc.b $FC, $F, $0, $13, $28
	dc.b $4, $0, $0, $23, $48
	dc.b $C, $6, $0, $24, $48
	dc.b $24, $0, $0, $2A, $48
	dc.b $1C, $D, $0, $2B, $8
	dc.b $1C, $E, $0, $33, $28
	dc.b $2C, $B, $0, $3F, $10
	dc.b $34, $8, $0, $4B, $28
	dc.b $3C, $1, $0, $4E, $8
	dc.b $3C, $4, $0, $50, $28
	dc.b $44, $0, $0, $52, $28
DATAV21JFHJ5PUP_4: dc.b $10
	dc.b $F8, $F, $2, $59, $9
	dc.b $F8, $7, $2, $69, $29
	dc.b $0, $3, $2, $71, $1
	dc.b $0, $3, $2, $75, $39
	dc.b $10, $1, $2, $79, $F9
	dc.b $18, $D, $2, $7B, $9
	dc.b $18, $7, $2, $83, $29
	dc.b $18, $3, $2, $8B, $41
	dc.b $20, $1, $2, $8F, $1
	dc.b $20, $3, $2, $91, $39
	dc.b $28, $8, $2, $95, $11
	dc.b $30, $7, $2, $98, $19
	dc.b $38, $1, $2, $A0, $11
	dc.b $38, $6, $2, $A2, $29
	dc.b $38, $1, $2, $A8, $41
	dc.b $40, $1, $2, $AA, $39
DATAV21JFHJ5PUP_5: dc.b $13
	dc.b $28, $E, $0, $B2, $38
	dc.b $18, $5, $0, $BE, $48
	dc.b $40, $8, $0, $C2, $38
	dc.b $48, $4, $0, $C5, $38
	dc.b $10, $F, $0, $53, $10
	dc.b $8, $4, $0, $63, $20
	dc.b $0, $B, $0, $65, $30
	dc.b $8, $0, $0, $71, $48
	dc.b $18, $0, $0, $72, $48
	dc.b $18, $5, $0, $73, $0
	dc.b $28, $2, $0, $77, $8
	dc.b $30, $F, $0, $7A, $10
	dc.b $20, $D, $0, $8A, $30
	dc.b $20, $1, $0, $92, $50
	dc.b $30, $8, $0, $94, $30
	dc.b $38, $E, $0, $97, $30
	dc.b $50, $D, $0, $A3, $8
	dc.b $50, $C, $0, $AB, $28
	dc.b $58, $8, $0, $AF, $28
DATAV21JFHJ5PUP_6: dc.b $F
	dc.b $EC, $F, $0, $C7, $E2
	dc.b $C, $F, $0, $D7, $E2
	dc.b $2C, $F, $0, $E7, $E2
	dc.b $EC, $F, $0, $F7, $2
	dc.b $C, $F, $1, $7, $2
	dc.b $2C, $F, $1, $17, $2
	dc.b $EC, $F, $1, $27, $22
	dc.b $C, $F, $1, $37, $22
	dc.b $2C, $F, $1, $47, $22
	dc.b $EC, $F, $1, $57, $42
	dc.b $C, $F, $1, $67, $42
	dc.b $2C, $F, $1, $77, $42
	dc.b $EC, $7, $1, $87, $62
	dc.b $C, $7, $1, $8F, $62
	dc.b $2C, $7, $1, $97, $62
DATAV21JFHJ5PUP_7: dc.b $F
	dc.b $EC, $F, $0, $C7, $E2
	dc.b $C, $F, $0, $D7, $E2
	dc.b $2C, $F, $0, $E7, $E2
	dc.b $EC, $F, $0, $F7, $2
	dc.b $C, $F, $1, $7, $2
	dc.b $2C, $F, $1, $17, $2
	dc.b $EC, $F, $1, $27, $22
	dc.b $C, $F, $1, $37, $22
	dc.b $2C, $F, $1, $47, $22
	dc.b $EC, $F, $1, $57, $42
	dc.b $C, $F, $1, $67, $42
	dc.b $2C, $F, $1, $77, $42
	dc.b $EC, $7, $1, $87, $62
	dc.b $C, $7, $1, $8F, $62
	dc.b $2C, $7, $1, $97, $62
	even