; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Mar 22 2025 11:29:00 GMT-0500 (Central Daylight Time)
; ================================================================================

DATAY1U343IF3L:
	dc.w DATAY1U343IF3L_0-DATAY1U343IF3L, DATAY1U343IF3L_1-DATAY1U343IF3L
	dc.w DATAY1U343IF3L_2-DATAY1U343IF3L, DATAY1U343IF3L_3-DATAY1U343IF3L
	dc.w DATAY1U343IF3L_4-DATAY1U343IF3L, DATAY1U343IF3L_5-DATAY1U343IF3L
	dc.w DATAY1U343IF3L_6-DATAY1U343IF3L, DATAY1U343IF3L_7-DATAY1U343IF3L
	dc.w DATAY1U343IF3L_8-DATAY1U343IF3L, DATAY1U343IF3L_9-DATAY1U343IF3L
	dc.w DATAY1U343IF3L_A-DATAY1U343IF3L, DATAY1U343IF3L_B-DATAY1U343IF3L
DATAY1U343IF3L_0: dc.b $5
	dc.b $E2, $F, $0, $0, $EB
	dc.b $2, $D, $0, $10, $EB
	dc.b $E2, $7, $0, $18, $B
	dc.b $2, $4, $0, $20, $B
	dc.b $A, $0, $0, $22, $B
DATAY1U343IF3L_1: dc.b $6
	dc.b $F2, $5, $0, $23, $F8
	dc.b $E2, $F, $0, $0, $EB
	dc.b $2, $D, $0, $10, $EB
	dc.b $E2, $7, $0, $18, $B
	dc.b $2, $4, $0, $20, $B
	dc.b $A, $0, $0, $22, $B
DATAY1U343IF3L_2: dc.b $5
	dc.b $E2, $F, $0, $0, $EB
	dc.b $2, $D, $0, $10, $EB
	dc.b $E2, $7, $0, $18, $B
	dc.b $2, $4, $0, $20, $B
	dc.b $A, $0, $0, $22, $B
DATAY1U343IF3L_3: dc.b $5
	dc.b $E2, $F, $0, $0, $EB
	dc.b $2, $D, $0, $10, $EB
	dc.b $E2, $7, $0, $18, $B
	dc.b $2, $4, $0, $20, $B
	dc.b $A, $0, $0, $22, $B
DATAY1U343IF3L_4: dc.b $6
	dc.b $F2, $5, $0, $27, $F8
	dc.b $E2, $F, $0, $0, $EB
	dc.b $2, $D, $0, $10, $EB
	dc.b $E2, $7, $0, $18, $B
	dc.b $2, $4, $0, $20, $B
	dc.b $A, $0, $0, $22, $B
DATAY1U343IF3L_5: dc.b $6
	dc.b $F2, $5, $0, $2B, $F8
	dc.b $E2, $F, $0, $0, $EB
	dc.b $2, $D, $0, $10, $EB
	dc.b $E2, $7, $0, $18, $B
	dc.b $2, $4, $0, $20, $B
	dc.b $A, $0, $0, $22, $B
DATAY1U343IF3L_6: dc.b $6
	dc.b $F2, $5, $0, $2F, $F8
	dc.b $E2, $F, $0, $0, $EB
	dc.b $2, $D, $0, $10, $EB
	dc.b $E2, $7, $0, $18, $B
	dc.b $2, $4, $0, $20, $B
	dc.b $A, $0, $0, $22, $B
DATAY1U343IF3L_7: dc.b $6
	dc.b $F2, $5, $0, $33, $F8
	dc.b $E2, $F, $0, $0, $EB
	dc.b $2, $D, $0, $10, $EB
	dc.b $E2, $7, $0, $18, $B
	dc.b $2, $4, $0, $20, $B
	dc.b $A, $0, $0, $22, $B
DATAY1U343IF3L_8: dc.b $6
	dc.b $F2, $5, $0, $37, $F8
	dc.b $E2, $F, $0, $0, $EB
	dc.b $2, $D, $0, $10, $EB
	dc.b $E2, $7, $0, $18, $B
	dc.b $2, $4, $0, $20, $B
	dc.b $A, $0, $0, $22, $B
DATAY1U343IF3L_9: dc.b $6
	dc.b $F2, $5, $0, $3B, $F8
	dc.b $E2, $F, $0, $0, $EB
	dc.b $2, $D, $0, $10, $EB
	dc.b $E2, $7, $0, $18, $B
	dc.b $2, $4, $0, $20, $B
	dc.b $A, $0, $0, $22, $B
DATAY1U343IF3L_A: dc.b $5
	dc.b $E2, $F, $0, $0, $EB
	dc.b $2, $D, $0, $10, $EB
	dc.b $E2, $7, $0, $18, $B
	dc.b $2, $4, $0, $20, $B
	dc.b $A, $0, $0, $22, $B
DATAY1U343IF3L_B: dc.b $1
	dc.b $FF, $D, $0, $3F, $F0
	even