; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Mar 21 2025 21:13:29 GMT-0500 (Central Daylight Time)
; ================================================================================

DATAA16Z12RYSAF:
	dc.w DATAA16Z12RYSAF_0-DATAA16Z12RYSAF, DATAA16Z12RYSAF_1-DATAA16Z12RYSAF
	dc.w DATAA16Z12RYSAF_2-DATAA16Z12RYSAF, DATAA16Z12RYSAF_3-DATAA16Z12RYSAF
	dc.w DATAA16Z12RYSAF_4-DATAA16Z12RYSAF, DATAA16Z12RYSAF_5-DATAA16Z12RYSAF
	dc.w DATAA16Z12RYSAF_6-DATAA16Z12RYSAF, DATAA16Z12RYSAF_7-DATAA16Z12RYSAF
	dc.w DATAA16Z12RYSAF_8-DATAA16Z12RYSAF, DATAA16Z12RYSAF_9-DATAA16Z12RYSAF
	dc.w DATAA16Z12RYSAF_A-DATAA16Z12RYSAF
DATAA16Z12RYSAF_0: dc.b $3
	dc.b $FC, $0, $0, $6D, $E8
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $4D, $F0
DATAA16Z12RYSAF_1: dc.b $4
	dc.b $E8, $D, $0, $C, $F0
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $4D, $F0
	dc.b $FC, $0, $0, $6D, $E8
DATAA16Z12RYSAF_2: dc.b $4
	dc.b $E9, $D, $0, $C, $F0
	dc.b $E9, $E, $0, $0, $F0
	dc.b $1, $F, $0, $5D, $F0
	dc.b $FD, $0, $0, $6D, $E8
DATAA16Z12RYSAF_3: dc.b $3
	dc.b $E8, $F, $0, $6E, $E8
	dc.b $8, $D, $0, $7E, $E8
	dc.b $F0, $5, $0, $86, $8
DATAA16Z12RYSAF_4: dc.b $4
	dc.b $E0, $F, $0, $8A, $E8
	dc.b $0, $C, $0, $9A, $E8
	dc.b $8, $6, $0, $9E, $F0
	dc.b $E8, $5, $0, $A4, $8
DATAA16Z12RYSAF_5: dc.b $4
	dc.b $E8, $D, $0, $14, $EC
	dc.b $E8, $1, $0, $1C, $C
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $4D, $F0
DATAA16Z12RYSAF_6: dc.b $7
	dc.b $E8, $D, $0, $14, $EC
	dc.b $E8, $1, $0, $1C, $C
	dc.b $4, $9, $8, $2E, $0
	dc.b $4, $5, $8, $34, $E8
	dc.b $F0, $F, $8, $1E, $F0
	dc.b $F1, $4, $8, $38, $10
	dc.b $F1, $4, $0, $38, $E0
DATAA16Z12RYSAF_7: dc.b $4
	dc.b $8, $D, $0, $A8, $E4
	dc.b $E8, $F, $0, $B0, $EC
	dc.b $8, $5, $0, $C0, $4
	dc.b $F0, $5, $0, $C4, $C
DATAA16Z12RYSAF_8: dc.b $5
	dc.b $C, $5, $0, $C8, $E4
	dc.b $E4, $F, $0, $CC, $EC
	dc.b $4, $C, $0, $DC, $EC
	dc.b $C, $5, $0, $E0, $FC
	dc.b $EC, $4, $0, $E4, $C
DATAA16Z12RYSAF_9: dc.b $8
	dc.b $E8, $D, $0, $14, $EC
	dc.b $E8, $1, $0, $1C, $C
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $4D, $F0
	dc.b $E0, $D, $3E, $CE, $F0
	dc.b $F0, $D, $3E, $CE, $F0
	dc.b $0, $D, $3E, $CE, $F0
	dc.b $10, $D, $3E, $CE, $F0
DATAA16Z12RYSAF_A: dc.b $3
	dc.b $EC, $D, $0, $3A, $E4
	dc.b $F4, $8, $0, $42, $4
	dc.b $EC, $D, $0, $45, $FC
	even